# Generated by Django 2.2.2 on 2020-10-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('number_of_passport', models.IntegerField(verbose_name='Серия и номер паспорта')),
                ('birthday', models.DateField(max_length=150, verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Место рождения')),
                ('date_of_passport', models.DateField(max_length=150, verbose_name='Дата получения паспорта')),
                ('code', models.SlugField(max_length=150, verbose_name='Код-подразделения')),
                ('issued_by', models.CharField(max_length=150, verbose_name='Кем выдан')),
                ('place_of_living', models.CharField(max_length=150, verbose_name='Место прописки')),
                ('file_of_pass', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_1', models.BooleanField(default=False)),
                ('rule_2', models.BooleanField(default=False)),
                ('rule_3', models.BooleanField(default=False)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='human.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_file', models.FileField(blank=True, upload_to='')),
                ('qualification', models.BooleanField(default=False)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='human.Investor')),
            ],
        ),
    ]
