# Generated by Django 2.2.2 on 2020-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='file_of_pass',
            field=models.FileField(upload_to='', verbose_name='Файл документа'),
        ),
    ]
