# Generated by Django 2.2.2 on 2020-10-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_auto_20201029_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='surname',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
    ]
