# Generated by Django 2.2.2 on 2020-10-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0004_auto_20201029_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='investor',
            new_name='invest',
        ),
        migrations.RenameField(
            model_name='rules',
            old_name='investor',
            new_name='invest',
        ),
    ]
