# Generated by Django 2.2.2 on 2020-10-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0005_auto_20201029_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='file_of_pass',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл документа'),
        ),
    ]
