# Generated by Django 2.2.2 on 2020-10-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0006_auto_20201029_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='number_of_passport',
            field=models.IntegerField(unique=True),
        ),
    ]
